@url = http://localhost:3000

# ==================== USUÁRIOS ====================
### Buscar todos os usuários
GET {{url}}/usuarios

### Buscar usuário por ID
GET {{url}}/usuarios/25

###
POST {{url}}/usuarios/login
Content-Type: application/json

{
  "email_usuario": "carlos@email.com",
  "senha_usuario": "carlos123"
}

###
POST {{url}}/usuarios/login
Content-Type: application/json

{
  "email_usuario": "gokugames@gmail.com",
  "senha_usuario": "kamehameha-ERRADO"
}

### Buscar usuário por ID
GET {{url}}/usuarios/6


### Criar usuário
POST {{url}}/usuarios
Content-Type: application/json

{
  "nome_usuario": "Insert pelo backend",
  "email_usuario": "insert@gmail.com",
  "senha_usuario": "123456",
  "telefone_usuario": "11000000000"
}

### Atualizar usuário
PUT {{url}}/usuarios/6
Content-Type: application/json

{
  "nome_usuario": "Teste Atualizado",
  "email_usuario": "teste.atualizado@gmail.com",
  "senha_usuario": "novasenha",
  "telefone_usuario": "11888888888",
  "id_status_usuario": "1"
}

### Deletar usuário
DELETE {{url}}/usuarios/1

###
PATCH {{url}}/usuarios/desativar/27

# ==================== CATEGORIAS ====================
### Buscar categorias
GET {{url}}/categorias

### Criar categoria
POST {{url}}/categorias
Content-Type: application/json

{
  "nome_categoria": "Alimentação"
}


# ==================== MÉTODOS ====================
### Buscar métodos
GET {{url}}/metodos

### Criar método
POST {{url}}/metodos
Content-Type: application/json

{
  "nome_metodo": "Cartão de Crédito"
}


# ==================== CONTAS ====================
### Buscar contas
GET {{url}}/contas

### Criar conta
POST {{url}}/contas
Content-Type: application/json

{
  "id_usuario": 1,
  "id_moeda": 1, 
  "nome_conta": "Conta Corrente Nubank",
  "saldo_conta": 1500.50
}


# ==================== TRANSAÇÕES ====================
### Buscar transações
GET {{url}}/transacoes

### Criar transação
POST {{url}}/transacoes
Content-Type: application/json

{
  "id_conta": 1,
  "id_categoria": 1,
  "id_metodo": 1,
  "id_carteira": 2,
  "valor": 150,
  "descricao": "Compra no mercado",
  "quitado": false,
  "arquivado": false,
  "data": "2026-05-04 16:52:11.299",
  "entrada": "true"
}

### Login Google
POST {{url}}/usuarios/login-google
Content-Type: application/json

{
  "idToken": "SEU_ID_TOKEN_GOOGLE_AQUI"
}

### Atualizar cadastro após login Google
PUT {{url}}/usuarios/1
Content-Type: application/json

{
  "telefone_usuario": "11999999999"
}
